version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    labels:
      - B0-low-priority
      - C0-breaks-nothing
      - D0-dependency

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
    labels:
      - B0-low-priority
      - C0-breaks-nothing
      - D0-dependency

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-images:
        patterns: ["*"]
    labels:
      - B0-low-priority
      - C0-breaks-nothing
      - D0-dependency
