version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - A3-technical
      - B0-low-priority
      - C0-breaks-nothing
      - D0-dependency

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - A3-technical
      - B0-low-priority
      - C0-breaks-nothing
      - D0-dependency

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    labels:
      - A3-technical
      - B0-low-priority
      - C0-breaks-nothing
      - D0-dependency
