name: License checks

on:
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - '**.sh'
      - 'scripts/check-spdx.sh'
      - '.github/workflows/licence.yml'
  push:
    branches: [main]
    paths:
      - '**.go'
      - '**.sh'
      - 'scripts/check-spdx.sh'
      - '.github/workflows/licence.yml'

permissions: read-all

concurrency:
  group: licence-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check SPDX headers
        run: |
          ./scripts/check-spdx.sh
